### ISSUE TITLE
installation qgis issue

### ISSUE THREAD

**Issue by filipdns** [lutraconsulting/qgis-quick-demo-app#1]
Hello,

I tried to follow your cmake command
cmake -G Ninja -DWITH_QUICK=TRUE -DWITH_GUI=FALSE -DWITH_DESKTOP=FALSE -DCMAKE_PREFIX_PATH=C:/qgis

but I received error with flex, grass, bison and many else missing.

why your command is not enough? what I have to install first before use your command?

Kind regards
Philippe

**Comment by PeterPetrik** [comment]
Windows in not yet supported for building android application, we haven't tried on that platform. Suggesting to install linux on virtual machine or use dockerized approach to build the application. Also check https://github.com/lutraconsulting/input and https://github.com/opengisch/QField for other android application based on qgsquick.

**Comment by edips** [comment]
Hi. After `ninja install` I got error on Manjaro:
`ninja: error: '../python/plugins/db_manager/db_plugins/postgis/plugins/versioning/pygui', needed by 'python/plugins/db_manager/db_plugins/postgis/plugins/versioning/ui_DlgVersioning.py', missing and no known rule to make it
`

**Comment by PeterPetrik** [comment]
Hi, can you post the cmake command used? For QgsQuick you do not need python bindings at all, best to use `-DWITH_BINDINGS=OFF` https://github.com/opengisch/OSGeo4A/blob/master/recipes/qgis/recipe.sh

**Comment by edips** [comment]
By the way I also got error on Lubuntu while using `ninja install:`
`https://github.com/lutraconsulting/qgis-quick-demo-app`
I used `cmake -G Ninja -DWITH_QUICK=TRUE -DWITH_GUI=FALSE -DWITH_DESKTOP=FALSE -DCMAKE_PREFIX_PATH=/home/edip/qgis ..`
I used CMAKE according to the documentation. Ok I will tell here after trying. Thanks.

**Comment by edips** [comment]
Sorry I got you wrong, after using `-DWITH_BINDINGS=OFF` it started to build :)

**Comment by edips** [comment]
By the way Lubuntu has problem converting *.ui files to *.py files

**Comment by edips** [comment]
When I install ninja install it fails as:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/edip/Desktop/qgis_android/QGIS/build
[160/161] Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/man/man1/qgis.1
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot set permissions on "/usr/local/man/man1/qgis.1"


FAILED: CMakeFiles/install.util 
cd /home/edip/Desktop/qgis_android/QGIS/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```
When I install as `sudo ninja install` it installs but `/home/edip/qgis` is empity

**Comment by edips** [comment]
Now I found the QML output:
```
edip@edips:~/Desktop/qgis_android/QGIS/build/output/qml/QgsQuick
.
├── libqgis_quick_plugin.so
├── qgsquickcheckbox.qml
├── qgsquickdatetime.qml
├── qgsquickexternalresource.qml
├── qgsquickfeatureform.qml
├── qgsquickfeatureformstyling.qml
├── qgsquickmapcanvas.qml
├── qgsquickmessagelog.qml
├── qgsquickphotopanel.qml
├── qgsquickpositionmarker.qml
├── qgsquickscalebar.qml
├── qgsquicktextedit.qml
├── qgsquickvaluemap.qml
└── qmldir
```

**Comment by edips** [comment]
I did steps to build QGIS, installed Qt for android and set sdk and ndk. Now I try to build Osgeo4A. After building Osgeo4A I got these errors:
```
xpat-2.0.1/doc/xmlwf.1 /home/edip/Desktop/qgis_android/OSGeo4A/stage/armeabi-v7a/man/man1
Leaving armeabi-v7a environment
Call build_geos
Entering in armeabi-v7a environment
Compiler found at /home/edip/Documents/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/edip/Desktop/qgis_android/OSGeo4A/build/geos/build-armeabi-v7a/CMakeFiles/CMakeOutput.log".

```
The log output is : 
```
The target system is: Android - 1 - armv7-a
The host system is: Linux - 4.15.0-20-generic - x86_64
```
Edit1:
I deleted geos from recipes and started building again, but this time I got the error from libtiff :
```
Entering in armeabi-v7a environment
Compiler found at /home/edip/Documents/crystax-ndk-10.3.2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
-- Building tiff version 4.0.9
-- libtiff library version 5.3.0
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/edip/Desktop/qgis_android/OSGeo4A/build/libtiff/build-armeabi-v7a/CMakeFiles/CMakeOutput.log".
```
I will delete libtiff from recipes and I will see if it builds.
My configuration:
```
export ANDROIDNDKVER=r12b
export ANDROIDAPI=16
export ANDROIDSDK="/home/edip/Documents/sdk"
export ANDROIDNDK="/home/edip/Documents/crystax-ndk-10.3.2"
export QT_ANDROID_BASE="/home/edip/Qt/5.11.2"
export O4A_qgis_DIR="/home/edip/Desktop/qgis_android/QGIS"
export ARCHES=("armeabi-v7a" )
```
Edit2: I think deleting recipes didn't work, it continues to give error, this time I got error for qca, deleted it from recipes, built again and got error for QtKeyChain.
Is it possible fix it? The problem is that cmake doesn't recognise Qt's  armeabi-v7a environment? Thanks

**Comment by PeterPetrik** [comment]
> ninja: build stopped: subcommand failed.
> ```
> When I install as `sudo ninja install` it installs but `/home/edip/qgis` is empity

To finish installation, you had to use `-DCMAKE_INSTALL_PREFIX=<my/great/local/folder/where/I/have/permissions>`.

**Comment by PeterPetrik** [comment]
> CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

You need to have `make` on PATH. make sure you have it installed, e.g.
`sudo apt-get install build-essential`

It is not good to delete recipes, you need them all. Start building them one-by-one, by using commands like

`./distribute -dqgis -mlibzip` 

or similar.

**Comment by edips** [comment]
I tried ./distribute -dqgis -mgeos it didn't work. I also tried docker method but the output APK didn't work for Android 8.0.
